import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Getting Started sidebar
  gettingStartedSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Using Standout sidebar
  usingStandoutSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Tutorials sidebar
  tutorialsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Troubleshooting sidebar
  troubleshootingSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
